#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"

// Images and Sprites generated by nin10kit.
#include "images/titleImageBg.h"
#include "images/circle.h"
#include "images/square.h"
#include "images/triangle.h"
#include "images/titleLogo1.h"
#include "images/titleLogo2.h"

// All States that the Game runs on
enum gba_state {
  START,
  STORY,
  PLAY,
  WIN,
  LOSE,
};



int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  // u32 previousButtons = BUTTONS;
  // u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  // declares status of each image being displayed to the screen
  // this is done to reduce tearing by only loading background images
  // when state is first reached
  int isTitleScreenDrawn = 1;

  // starts game loop by displaying title screen
  drawFullScreenImageDMA(titleImageBg);

  // draws shapes,
  titleAnimationImage circleImage;
  titleAnimationImage squareImage;
  titleAnimationImage triangleImage;
  titleAnimationImage titleLogoImage;
  titleAnimationImage titleOtherLogoImage;

  titleAnimationImage *circleImagePtr = &circleImage;
  titleAnimationImage *squareImagePtr = &squareImage;
  titleAnimationImage *triangleImagePtr = &triangleImage;
  titleAnimationImage *titleLogoImagePtr = &titleLogoImage;
  titleAnimationImage *titleOtherLogoImagePtr = &titleOtherLogoImage;

  initializeTitleAnimation(circleImagePtr, squareImagePtr, triangleImagePtr, titleLogoImagePtr, titleOtherLogoImagePtr);


  int animationPhase = 1;



  while (1) {
    // currentButtons = BUTTONS; // Load the current state of the buttons

    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    // 1. Game Logic
    switch (state) {
      case START:
        // Start State
        switch (animationPhase) {
          case 1:
            if (circleImage.row < SHAPE_ANIMATION_BASELINE_1) {
              circleImage.row += circleImage.playerSpeed;
            } else {
              circleImage.isFinishedMoving = 1;
            }
            break;
        case 2:
            if (squareImage.row > SHAPE_ANIMATION_BASELINE_1) {
              squareImage.row -= squareImage.playerSpeed;
            } else {
              squareImage.isFinishedMoving = 1;
            }
            break;
        case 3:
            if (triangleImage.row < SHAPE_ANIMATION_BASELINE_1) {
              triangleImage.row += triangleImage.playerSpeed;
            } else {
              triangleImage.isFinishedMoving = 1;
            }
            break;
        case 4:
            if (circleImage.row != SHAPE_ANIMATION_BASELINE_2) {
              circleImage.row += circleImage.playerSpeed;
              squareImage.row += squareImage.playerSpeed;
              triangleImage.row += triangleImage.playerSpeed;
              pause(ANIMATION_DELAY_MS);
            } else {
              circleImage.isFinishedMoving = 1;
            }
            break;
        case 5:
            break;
        }

        break;
      case STORY:
          break;
      case PLAY:
          break;
      case WIN:
        break;
      case LOSE:
        break;
    }

    // 2. Update Video buffer and Draw to the screen
    waitForVBlank();
    switch (state) {
      case START:
        // Start State

          // Start loading in background title screen animations
          if (!isTitleScreenDrawn) {
            drawFullScreenImageDMA(titleImageBg);
            initializeTitleAnimation(circleImagePtr, squareImagePtr, triangleImagePtr, titleLogoImagePtr, titleOtherLogoImagePtr);
            isTitleScreenDrawn = 1;
          }

        switch (animationPhase) {
          case 1:
            if (!circleImage.isFinishedMoving) {
              undrawImageDMA(circleImage.prevRow, circleImage.prevCol,circleImage.width, circleImage.height,titleImageBg);
              drawImageDMA(circleImage.row, circleImage.col, circleImage.width, circleImage.height, circle);
              circleImage.prevRow = circleImage.row;
              circleImage.prevCol = circleImage.col;
            } else {
              animationPhase = 2;
            }
            break;
         case 2:
            if (!squareImage.isFinishedMoving) {
              undrawImageDMA(squareImage.prevRow, squareImage.prevCol, squareImage.width, squareImage.height, titleImageBg);
              drawImageDMA(squareImage.row, squareImage.col, squareImage.width, squareImage.height, square);
              squareImage.prevRow = squareImage.row;
              squareImage.prevCol = squareImage.col;
            } else {
              animationPhase = 3;
            }
            break;
        case 3:
            if (!triangleImage.isFinishedMoving) {
              undrawImageDMA(triangleImage.prevRow, triangleImage.prevCol, triangleImage.width, triangleImage.height, titleImageBg);
              drawImageDMA(triangleImage.row, triangleImage.col, triangleImage.width, triangleImage.height, triangle);
              triangleImage.prevRow = triangleImage.row;
              triangleImage.prevCol = triangleImage.col;
            } else {
              pause(SECONDS_TO_MS(3));
              circleImage.isFinishedMoving = 0;
              animationPhase = 4;
            }
            break;
        case 4:
            if (!circleImage.isFinishedMoving) {
              undrawImageDMA(circleImage.prevRow, circleImage.prevCol,circleImage.width, circleImage.height,titleImageBg);
              drawImageDMA(circleImage.row, circleImage.col, circleImage.width, circleImage.height, circle);
              circleImage.prevRow = circleImage.row;
              circleImage.prevCol = circleImage.col;

              undrawImageDMA(squareImage.prevRow, squareImage.prevCol, squareImage.width, squareImage.height, titleImageBg);
              drawImageDMA(squareImage.row, squareImage.col, squareImage.width, squareImage.height, square);
              squareImage.prevRow = squareImage.row;
              squareImage.prevCol = squareImage.col;

              undrawImageDMA(triangleImage.prevRow, triangleImage.prevCol, triangleImage.width, triangleImage.height, titleImageBg);
              drawImageDMA(triangleImage.row, triangleImage.col, triangleImage.width, triangleImage.height, triangle);
              triangleImage.prevRow = triangleImage.row;
              triangleImage.prevCol = triangleImage.col;
            } else {
              animationPhase = 5;
            }
            break;
        case 5:
            if (!titleLogoImage.isDisplayed) {
              drawTitleAnimationDMA(titleLogoImage.row, titleLogoImage.col, titleLogoImage.width, titleLogoImage.height, titleLogo1, 125);
              drawTitleAnimationDMA(titleOtherLogoImage.row, titleOtherLogoImage.col, titleOtherLogoImage.width, titleOtherLogoImage.height, titleLogo2, 50);
              drawString(135, 30, "Click START to start the game!", BLACK);
              titleLogoImage.isDisplayed = 1;
            }
        }

          // tells user to slick START button to initialize title
          // drawString(10, 30, "Click START to start the game!", BLACK);
          break;
      case STORY:
        break;
      case PLAY:
        break;
      case WIN:
          break;
      case LOSE:
        break;
    }

    // 3. Choose next state
    switch (state) {
      case START:

        break;
      case PLAY:

          break;
      case STORY:

          break;
      case WIN:

          break;
      case LOSE:
        break;
    }
    // previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}

void pause(int milliseconds) {
  int n = milliseconds / 16;
  for (int i = 0; i < n; i++) {
    waitForVBlank();
  }
}

void initializeTitleAnimation(titleAnimationImage *circle,
  titleAnimationImage *square,
  titleAnimationImage *triangle,
  titleAnimationImage *titleLogo,
  titleAnimationImage *titleOtherLogo) {
  circle->row = 0;
  circle->col = 30;
  circle->prevRow = 0;
  circle->prevCol = 30;
  circle->height = 50;
  circle->width = 50;
  circle->playerSpeed = 1;
  circle->isFinishedMoving = 0;

  square->row = 110;
  square->col = 90;
  square->prevRow = 110;
  square->prevCol = 90;
  square->height = 50;
  square->width = 50;
  square->playerSpeed = 1;
  square->isFinishedMoving = 0;

  triangle->row = 0;
  triangle->col = 150;
  triangle->prevRow = 0;
  triangle->prevCol = 150;
  triangle->height = 50;
  triangle->width = 50;
  triangle->playerSpeed = 1;
  triangle->isFinishedMoving = 0;

  titleLogo->row = 20;
  titleLogo->col = 20;
  titleLogo->height = 45;
  titleLogo->width = 95;
  titleLogo->isDisplayed = 0;

  titleOtherLogo->row = 25;
  titleOtherLogo->col = 120;
  titleOtherLogo->height = 36;
  titleOtherLogo->width = 100;
  titleOtherLogo->isDisplayed = 0;
}