#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"

// Images and Sprites generated by nin10kit.
#include "images/titleImageBg.h"
#include "images/circle.h"
#include "images/square.h"
#include "images/triangle.h"

#define SHAPE_ANIMATION_BASELINE 55
// All States that the Game runs on
enum gba_state {
  START,
  STORY,
  PLAY,
  WIN,
  LOSE,
};

// function that pauses the game in seconds
void pause(int milliseconds) {
  int n = milliseconds / 16;
  for (int i = 0; i < n; i++) {
    waitForVBlank();
  }
}

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  // u32 previousButtons = BUTTONS;
  // u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  // declares status of each image being displayed to the screen
  // this is done to reduce tearing by only loading background images
  // when state is first reached
  int isTitleScreenDrawn = 1;

  // starts game loop by displaying title screen
  drawFullScreenImageDMA(titleImageBg);

  // draws shapes,
  struct titleAnimationImage circleImage;
  struct titleAnimationImage squareImage;
  struct titleAnimationImage triangleImage;
  // struct titleAnimationImage shapes[] = { circleImage, squareImage, triangleImage };
  //
  // for (int i = 0; i < 3; i++) {
  //   shapes[i].row = 0;
  //   shapes[i].col = 30 + i * 60;
  //   shapes[i].prevRow = 0;
  //   shapes[i].prevCol = 30 + i * 60;
  //   shapes[i].height = 50;
  //   shapes[i].width = 50;
  //   shapes[i].playerSpeed = 1;
  // }
  circleImage.row = 0;
  circleImage.col = 30;
  circleImage.prevRow = 0;
  circleImage.prevCol = 30;
  circleImage.height = 50;
  circleImage.width = 50;
  circleImage.playerSpeed = 1;
  circleImage.isFinishedMoving = 0;

  squareImage.row = 110;
  squareImage.col = 30 + 60;
  squareImage.prevRow = 110;
  squareImage.prevCol = 30 + 60;
  squareImage.height = 50;
  squareImage.width = 50;
  squareImage.playerSpeed = 1;
  squareImage.isFinishedMoving = 0;

  triangleImage.row = 0;
  triangleImage.col = 30 + 120;
  triangleImage.prevRow = 0;
  triangleImage.prevCol = 30 + 120;
  triangleImage.height = 50;
  triangleImage.width = 50;
  triangleImage.playerSpeed = 1;
  triangleImage.isFinishedMoving = 0;



  int currentShape = 1;



  while (1) {
    // currentButtons = BUTTONS; // Load the current state of the buttons

    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    // 1. Game Logic
    switch (state) {
      case START:
        // Start State
        switch (currentShape) {
          case 1:
            if (circleImage.row < SHAPE_ANIMATION_BASELINE) {
              circleImage.row += circleImage.playerSpeed;
              // pause(300);
            } else {
              circleImage.isFinishedMoving = 1;
              currentShape = 2;
            }
            break;
        case 2:
            if (squareImage.row > SHAPE_ANIMATION_BASELINE) {
              squareImage.row -= squareImage.playerSpeed;
              // pause(300);
            } else {
              squareImage.isFinishedMoving = 1;
              currentShape = 3;
            }
            break;
        case 3:
            if (triangleImage.row < SHAPE_ANIMATION_BASELINE) {
              triangleImage.row += triangleImage.playerSpeed;
              // pause(300);
            } else {
              triangleImage.isFinishedMoving = 1;
              currentShape = 4;
            }
            break;
        }

        break;
      case STORY:
          break;
      case PLAY:
          break;
      case WIN:
        break;
      case LOSE:
        break;
    }

    // 2. Update Video buffer and Draw to the screen
    waitForVBlank();
    switch (state) {
      case START:
        // Start State

          // draws tile screen background
          if (!isTitleScreenDrawn) {
            drawFullScreenImageDMA(titleImageBg);
            isTitleScreenDrawn = 1;
          }

        switch (currentShape) {
          case 1:
            if (!circleImage.isFinishedMoving) {
              undrawImageDMA(circleImage.prevRow, circleImage.prevCol,circleImage.width, circleImage.height,titleImageBg);
              drawImageDMA(circleImage.row, circleImage.col, circleImage.width, circleImage.height, circle);
              circleImage.prevRow = circleImage.row;
              circleImage.prevCol = circleImage.col;
            }
            break;
         case 2:
            if (!squareImage.isFinishedMoving) {
              undrawImageDMA(squareImage.prevRow, squareImage.prevCol, squareImage.width, squareImage.height, titleImageBg);
              drawImageDMA(squareImage.row, squareImage.col, squareImage.width, squareImage.height, square);
              squareImage.prevRow = squareImage.row;
              squareImage.prevCol = squareImage.col;
            }
            break;
        case 3:
            if (!triangleImage.isFinishedMoving) {
              undrawImageDMA(triangleImage.prevRow, triangleImage.prevCol, triangleImage.width, triangleImage.height, titleImageBg);
              drawImageDMA(triangleImage.row, triangleImage.col, triangleImage.width, triangleImage.height, triangle);
              triangleImage.prevRow = triangleImage.row;
              triangleImage.prevCol = triangleImage.col;
            }
            break;

        }

          // tells user to slick START button to initialize title
          // drawString(10, 30, "Click START to start the game!", BLACK);
          break;
      case STORY:
        break;
      case PLAY:
        break;
      case WIN:
          break;
      case LOSE:
        break;
    }

    // 3. Choose next state
    switch (state) {
      case START:

        break;
      case PLAY:

          break;
      case STORY:

          break;
      case WIN:

          break;
      case LOSE:
        break;
    }
    // previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}
