#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"

// Images and Sprites generated by nin10kit.
#include "images/titleImageBg.h"
#include "images/circle.h"
#include "images/square.h"
#include "images/triangle.h"


// All States that the Game runs on
enum gba_state {
  START,
  STORY,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  // u32 previousButtons = BUTTONS;
  // u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;




  // player properties
  // struct player user;
  // user.width = 15;
  // user.height = 15;
  // user.playerSpeed = 2;


  // declares status of each image being displayed to the screen
  // this is done to reduce tearing by only loading background images
  // when state is first reached
  int isTitleScreenDrawn = 1;

  // starts game loop by displaying title screen
  drawFullScreenImageDMA(titleImageBg);

  // draws shapes, this is currently here for debugging purposes
  //  drawImageDMA(80, 100, 50, 50, circle);
  //  drawImageDMA(150, 100, 50, 50, triangle);
  //  drawImageDMA(175, 100, 50, 50, square);


  while (1) {
    // currentButtons = BUTTONS; // Load the current state of the buttons

    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    // 1. Game Logic
    switch (state) {
      case START:
        // Start State
        break;
      case STORY:
          break;
      case PLAY:
          break;
      case WIN:
        break;
      case LOSE:
        break;
    }

    // 2. Update Video buffer and Draw to the screen
    waitForVBlank();
    switch (state) {
      case START:
        // Start State

          // draws tile screen background
          if (!isTitleScreenDrawn) {
            drawFullScreenImageDMA(titleImageBg);
            isTitleScreenDrawn = 1;
          }

          // tells user to slick START button to initialize title
          drawString(10, 30, "Click START to start the game!", BLACK);
          break;
      case STORY:
        break;
      case PLAY:
        break;
      case WIN:
          break;
      case LOSE:
        break;
    }

    // 3. Choose next state
    switch (state) {
      case START:

        break;
      case PLAY:

          break;
      case STORY:

          break;
      case WIN:

          break;
      case LOSE:
        break;
    }
    // previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}

// make BW filter
// for(int r=0; r<height; r++) {
// 	for(int c=0; c<width; c++) {
// 		u16 *src = image + r * width + c;
// 		u16 red = *src & (0b11111 << 10);
// 		u16 bw = red | red >> 5 | red >> 10;
// 		videoBuffer[OFFSET(row+r, col+c, 240)] = bw;
// 	}
// }

// unsigned short grayscale(unsigned short pixel) {
//     unsigned int r, g, b, avg;
//     b = (pixel >> 10) & 0x1f;
//     g = (pixel >> 5) & 0x1f;
//     r = pixel & 0x1f;
//     avg = (r + g + b) / 3;
//     return avg << 10 | avg << 5 | avg;
// }
